### ISSUE TITLE
Write more tests

### ISSUE THREAD

**Issue by volovyks** [near/mpc#487]
### Description
```[tasklist]
### Tasks
- [ ] https://github.com/near/mpc-recovery/issues/555
- [x] Test when one node is offline
- [ ] https://github.com/near/mpc-recovery/issues/559
- [ ] https://github.com/near/mpc-recovery/issues/564
- [x] Find out how many nodes we can have in the network (can be == to threshold)
- [ ] https://github.com/near/mpc/issues/642
- [ ] https://github.com/near/mpc/issues/641
- [ ] https://github.com/near/mpc/issues/639
```

**Comment by volovyks** [comment]
closing in favour of #663
