### ISSUE TITLE
Contract audit

### ISSUE THREAD

**Issue by volovyks** [near/mpc#570]
### Description

```[tasklist]
### Tasks
- [ ] https://github.com/near/mpc-recovery/issues/571
- [ ] https://github.com/near/mpc-recovery/pull/558
- [ ] https://github.com/near/mpc-recovery/issues/473
- [ ] Do the audit
```
