### ISSUE TITLE
Updated README

### ISSUE THREAD

**Issue by volovyks** [near/mpc#601]
### Description
Update readme for Multi-chain project

```[tasklist]
### Tasks
- [ ] https://github.com/near/mpc-recovery/issues/603
- [ ] https://github.com/near/mpc-recovery/issues/473
- [ ] https://github.com/near/mpc-recovery/issues/593
- [ ] Create README and short contract API doccumentation
- [ ] Add a list of environments and short description of each one
```

**Comment by volovyks** [comment]
Draft for evs description:

- Dev testnet network (8 nodes), mostly used by our backend team, represents current develop.
    - NEAR AccId: v5.multichain-mpc-dev.testnet
- Partner testnet network (8 nodes):
    - NEAR AccId: v2.multichain-mpc.testnet
- Partner mainnet network (8 nodes)
    - NEAR AccId: not released yet

v1, v2, etc. is a version of the contract. We will change it each time we can not upgrade the contract. Ideally never.
For development, you should use v2.multichain-mpc.testnet. (edi
