### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by volovyks** [near/mpc#817]
```[tasklist]
### Tasks
- [ ] https://github.com/near/mpc/issues/819
- [ ] https://github.com/near/mpc/issues/820
- [ ] https://github.com/near/mpc/issues/821
- [ ] https://github.com/near/mpc/issues/822
- [ ] https://github.com/near/mpc/issues/823
```
